[module/bright]
type = custom/script
exec = $HOME/.config/polybar/scripts/bright.sh
scroll-up = "$HOME/.config/polybar/scripts/bright.sh +"
scroll-down = "$HOME/.config/polybar/scripts/bright.sh -"
interval = 2
format-prefix = 
format-background = ${color.background}

; format-prefix-foreground = #00cc00
; format-underline = #00cc00
; format-foreground = #00cc00